### PR TITLE
feat: eng 523 jobs page

### PR DESCRIPTION
**Pull request by VictorOfCode**
created a dynamic jobs page route to connect to ecosystems page. ecosystems page should accept jenny's company group manager.

### CODE REVIEW

**Comment by deus-ex-rivina** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **victorofcode**
You can assign the PR to them by writing `/assign @victorofcode` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=rivierapartners%2Fpresidio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/rivierapartners/presidio/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | ee588e60d8273a266320892c21760ef7c9a768cc | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-gxbx9) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | c489d8e459eb8dd236e0711063705054f440594c | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-zjj4g) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | c0b86e8771c59af09ca1e69e954daf027715f04c | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-6svth) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | c661a8601ac1e9235cc9dc37eed292a4d98efd12 | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-rljjq) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | c661a8601ac1e9235cc9dc37eed292a4d98efd12 | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-7l9bj) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by deus-ex-rivina** [comment]
@VictorOfCode: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 4cf9809230e121e9113aa2c877c05506f53af068 | [link](http://dashboard-jx.jx.riviapps.com/namespaces/jx/pipelineruns/ivierapartners-presidio-pr-19-pr-tp6zw) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by patrickleet** [comment]
hi - it'd be good to not merge branches that don't pass the build

**Pull request merged**
