### PR TITLE
feat: switch windi for tailwindcss JIT

### PR DESCRIPTION
**Pull request by patrickleet**
Signed-off-by: Patrick Lee Scott <pat@patscott.io>

### CODE REVIEW

**Review by pboling — COMMENTED** [review]
LGTM, but will let @blueberry-hamster approve

**Comment by deus-ex-rivina** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=rivierapartners%2Fpresidio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/rivierapartners/presidio/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by deus-ex-rivina** [comment]
:star: PR built and available in a preview **rivierapartners-presidio-pr-2** [here](http://presidio.jx-rivierapartners-presidio-pr-2.jx.riviapps.com)

**Review by blueberry-hamster — APPROVED** [review]
nice, thanks~

**Comment by deus-ex-rivina** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[blueberry-hamster](https://github.com/rivierapartners/presidio/pull/2#pullrequestreview-688710255 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=rivierapartners%2Fpresidio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/rivierapartners/presidio/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by patrickleet** [comment]
The approval won't work automatically for this one as it's based on the OWNERS file in the branch it's being merged into, which isn't there yet, as it was added here.

**Pull request merged**
